### ISSUE TITLE
Implement OUT resource-type API

### ISSUE THREAD

**Issue by mikemimik** [mikemimik/aws-rds-snapshot-resource#2]
### Resource Type:
```yaml
resources:
- name: rds-snapshot
  type: rds-snapshot-resource
  source:
    aws_access_key: ((aws-access-key-id))
    aws_secret_access_key: ((aws-secret-access-key))
    aws_region: us-east-1
    rds_instance_identifier: some-rds-name
    tags:
      - Key: some-tag
        Value: some-value
      - Key: other-tag
        Value: other-value
```

### Plan Usage:
```yaml
plan:
- put: rds-snapshot
  params:
    snapshot_identifier: name-of-the-snapshot
```
